print("Hello World \n") 
print("Hello again \n")
print("I like typing this. \n")
print("This is fun. \n")
#print('ya! Printing \n')
#print("I'd much rather you 'not'. \n")
print('I "said" do not touch this. \n')